@startuml
title Art player initialization
autonumber 1.1
skinparam pageMargin 10

participant Browser
participant ArtPiece
participant API
participant PlatformAdapter
participant TimeProvider

activate Browser
	== Startup ==

	Browser -> Browser : Load HTML w/ GenArt API script
	Browser -> PlatformAdapter : Load platform adapter
	Browser --> TimeProvider : Load custom timing provider
	note right
		optional, by default uses
		`timingProviderRAF()`
	end note
	Browser -> ArtPiece : Load art piece script
	activate API
		API -> API : Initialize
		activate PlatformAdapter
		PlatformAdapter -> PlatformAdapter : Initialize (optional)
		PlatformAdapter -> PlatformAdapter : Initialize PRNG
		note left : Seeded/deterministic
		PlatformAdapter -> PlatformAdapter : Set execution mode
		note left : Play / Preview / Edit
		TimeProvider -> TimeProvider : Initialize (optional)
		
		PlatformAdapter -> API : Register adapter
		note right : `$genart.setAdapter()`
		deactivate PlatformAdapter
	deactivate API

	activate ArtPiece
		ArtPiece -> API : Wait for adapter registration
		note left : `await $genart.waitForAdapter()`
		API --> ArtPiece : Return when adapter available...
		ArtPiece -> API : Declare & register param specs
		activate API
			note left
				`$genart.setParams({...})`
			end note
			API -> API : Validate params specs
			note right : Ensure valid param types
			API -> API : Add missing default values
			note right: Randomize missing defaults
			API -> PlatformAdapter : Pass param specs
			note right : `adapter.setParams({...})`
			activate PlatformAdapter
				PlatformAdapter -> PlatformAdapter : Load & parse params
				PlatformAdapter --> API : return true if successful
				API -> PlatformAdapter : Update/augment params
				note right
					source param values via
					platform-specific means
				end note
				PlatformAdapter --> API : Param values
			deactivate PlatformAdapter

			API -> API : Validate & apply param overrides
			API -->> API : Emit `genart:setparams` message
			note right : Sent to current & parent window
			API --> ArtPiece : Typesafe param getter function
			note left : ArtPiece uses this function\nto obtain param values
		deactivate API

		ArtPiece -> API : Request screen config
		API -> PlatformAdapter : Request screen config
		note right : optionally define resolution
		PlatformAdapter --> API : Config
		API --> ArtPiece : Config
		ArtPiece -> ArtPiece : Initialize
		ArtPiece -> API : Get param value
		activate API
			API -> API : Delegate to param impl
			API --> ArtPiece : Param value
		deactivate API

		== Animation start ==
		ArtPiece ->	API : Register update/draw function
		API -> API : Transition state to `ready`
		API --> API : Emit `genart:statechange` message
		activate PlatformAdapter
			PlatformAdapter -> PlatformAdapter : Process `ready` state change
			PlatformAdapter -> API : Start anim loop
			note right : `$genart.start()`
		deactivate PlatformAdapter
	deactivate ArtPiece

	activate API
		API -> TimeProvider : Start (reset timestamp)
		loop Animation loop
			API -> TimeProvider : Queue next frame update
			note right : Default: `requestAnimationFrame()`
			TimeProvider --> API : Trigger update with current time & frame
			API -> ArtPiece : Call update w/ timestamp
			ArtPiece -> ArtPiece : Generate next frame
			ArtPiece -> API : Trigger screen capture (once, after X seconds)
			note left: `$genart.capture(canvas)`
			API -> PlatformAdapter : Handle screen capture
			note right : Optional, platform specific
			API --> API : Emit `genart:capture` message
		end
	deactivate API

deactivate Browser

@enduml