//! Generated by @thi.ng/wasm-api-bindgen at 2024-11-11T10:06:25.816Z
//! DO NOT EDIT!

const std = @import("std");
const bindgen = @import("wasm-api-bindgen");

pub const OptionSlice = bindgen.Slice([]Option, [*]Option);
pub const ConstOptionSlice = bindgen.Slice([]const Option, [*]const Option);

pub const Param = extern struct {
    type: bindgen.ConstStringPtr,
    id: bindgen.ConstStringPtr,
    name: bindgen.ConstStringPtr,
    desc: bindgen.ConstStringPtr,
    doc: ?bindgen.ConstStringPtr = null,
    update: UpdateBehavior = .event,
    body: ParamBody,
};

pub const ParamBody = extern union {
    choice: ChoiceParam,
    color: ColorParam,
    range: RangeParam,
};

pub const UpdateBehavior = enum(u8) {
    event,
    reload,
};

pub const ChoiceParam = extern struct {
    default: ?bindgen.ConstStringPtr = null,
    /// In Zig, use `genart.options()` to wrap
    options: ConstOptionSlice,
};

pub const Option = extern struct {
    value: bindgen.ConstStringPtr,
    label: ?bindgen.ConstStringPtr = null,
};

pub const ColorParam = extern struct {
    default: ?bindgen.ConstStringPtr = null,
};

pub const RangeParam = extern struct {
    default: f64 = std.math.inf(f64),
    min: f64 = 0,
    max: f64 = 100,
    step: f64 = 1,
    exponent: f64 = 1,
};
